/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "JuceHeader.h"
#include "PluginProcessor.h"

class MainTabs;

//==============================================================================
/**
*/
class Pfm2AudioProcessorEditor  : public AudioProcessorEditor, public Timer
{
public:
    Pfm2AudioProcessorEditor (Pfm2AudioProcessor* ownerFilter);
    ~Pfm2AudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void timerCallback ();
	void mustUpdateUI();

private:
	bool uiOutOfSync;
    MainTabs * mainTabs;
};


#endif  // PLUGINEDITOR_H_INCLUDED
