/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

#include "UI/MainTabs.h"

//==============================================================================
Pfm2AudioProcessorEditor::Pfm2AudioProcessorEditor (Pfm2AudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
    addAndMakeVisible (mainTabs = new MainTabs() );
    // This is where our plugin's editor size is set.
    setSize (900, 710);
}

Pfm2AudioProcessorEditor::~Pfm2AudioProcessorEditor()
{
    delete mainTabs;
}

//==============================================================================
void Pfm2AudioProcessorEditor::paint (Graphics& g)
{
}


void Pfm2AudioProcessorEditor::handleIncomingMidiBuffer(MidiBuffer &buffer, int numberOfSamples)
{
    mainTabs->handleIncomingMidiBuffer(buffer, numberOfSamples);
}
