/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/


#include "../JuceLibraryCode/JuceHeader.h"
#include "pfm2Window.h"
#include "../../Plugin/Source/UI/PreenLookAndFeel.h"

//==============================================================================
class pfm2EditorApplication  : public JUCEApplication
{
public:
    //==============================================================================
    pfm2EditorApplication() {
    }

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        // Add your application's initialisation code here...
        myLookAndFeel = new preenfmLookAndFeel();
        LookAndFeel::setDefaultLookAndFeel(myLookAndFeel);

        mainWindow = new StandalonePFM2Window("TEST", Colours::lightblue, nullptr);
        mainWindow->setVisible (true);
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
        delete mainWindow;
        delete myLookAndFeel;
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    StandalonePFM2Window* mainWindow;
    LookAndFeel* myLookAndFeel;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (pfm2EditorApplication)


