/*
  ==============================================================================

    PreenNrpn.h
    Created: 8 Apr 2014 9:37:07pm
    Author:  xhosxe

  ==============================================================================
 */

#ifndef PREENNRPN_H_INCLUDED
#define PREENNRPN_H_INCLUDED

enum {
	PREENFM2_NRPN_ALGO = 0,
	PREENFM2_NRPN_VELOCITY,
	PREENFM2_NRPN_VOICE,
	PREENFM2_NRPN_GLIDE,

	PREENFM2_NRPN_IM1 = 4,
	PREENFM2_NRPN_IM1_VELOCITY,
	PREENFM2_NRPN_IM2,
	PREENFM2_NRPN_IM2_VELOCITY,
	PREENFM2_NRPN_IM3,
	PREENFM2_NRPN_IM3_VELOCITY,
	PREENFM2_NRPN_IM4,
	PREENFM2_NRPN_IM4_VELOCITY,
	PREENFM2_NRPN_IM5 ,
	PREENFM2_NRPN_IM5_VELOCITY,

	PREENFM2_NRPN_MIX1  = 16,
	PREENFM2_NRPN_PAN1,
	PREENFM2_NRPN_MIX2,
	PREENFM2_NRPN_PAN2,
	PREENFM2_NRPN_MIX3,
	PREENFM2_NRPN_PAN3,
	PREENFM2_NRPN_MIX4,
	PREENFM2_NRPN_PAN4,
	PREENFM2_NRPN_MIX5,
	PREENFM2_NRPN_PAN5,
	PREENFM2_NRPN_MIX6,
	PREENFM2_NRPN_PAN6,

	PREENFM2_NRPN_OPERATOR1_SHAPE = 44,
	PREENFM2_NRPN_OPERATOR1_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR1_FREQUENCY,
	PREENFM2_NRPN_OPERATOR1_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_OPERATOR2_SHAPE,
	PREENFM2_NRPN_OPERATOR2_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR2_FREQUENCY,
	PREENFM2_NRPN_OPERATOR2_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_OPERATOR3_SHAPE,
	PREENFM2_NRPN_OPERATOR3_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR3_FREQUENCY,
	PREENFM2_NRPN_OPERATOR3_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_OPERATOR4_SHAPE,
	PREENFM2_NRPN_OPERATOR4_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR4_FREQUENCY,
	PREENFM2_NRPN_OPERATOR4_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_OPERATOR5_SHAPE,
	PREENFM2_NRPN_OPERATOR5_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR5_FREQUENCY,
	PREENFM2_NRPN_OPERATOR5_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_OPERATOR6_SHAPE,
	PREENFM2_NRPN_OPERATOR6_FREQUENCY_TYPE,
	PREENFM2_NRPN_OPERATOR6_FREQUENCY,
	PREENFM2_NRPN_OPERATOR6_FREQUENCY_FINE_TUNE,

	PREENFM2_NRPN_ENV1_ATTK = 68,
	PREENFM2_NRPN_ENV1_ATTK_LEVEL,
	PREENFM2_NRPN_ENV1_DECAY,
	PREENFM2_NRPN_ENV1_DECAY_LEVEL,
	PREENFM2_NRPN_ENV1_SUSTAIN,
	PREENFM2_NRPN_ENV1_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV1_RELEASE,
	PREENFM2_NRPN_ENV1_RELEASE_LEVEL,

	PREENFM2_NRPN_ENV2_ATTK,
	PREENFM2_NRPN_ENV2_ATTK_LEVEL,
	PREENFM2_NRPN_ENV2_DECAY,
	PREENFM2_NRPN_ENV2_DECAY_LEVEL,
	PREENFM2_NRPN_ENV2_SUSTAIN,
	PREENFM2_NRPN_ENV2_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV2_RELEASE,
	PREENFM2_NRPN_ENV2_RELEASE_LEVEL,

	PREENFM2_NRPN_ENV3_ATTK,
	PREENFM2_NRPN_ENV3_ATTK_LEVEL,
	PREENFM2_NRPN_ENV3_DECAY,
	PREENFM2_NRPN_ENV3_DECAY_LEVEL,
	PREENFM2_NRPN_ENV3_SUSTAIN,
	PREENFM2_NRPN_ENV3_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV3_RELEASE,
	PREENFM2_NRPN_ENV3_RELEASE_LEVEL,

	PREENFM2_NRPN_ENV4_ATTK,
	PREENFM2_NRPN_ENV4_ATTK_LEVEL,
	PREENFM2_NRPN_ENV4_DECAY,
	PREENFM2_NRPN_ENV4_DECAY_LEVEL,
	PREENFM2_NRPN_ENV4_SUSTAIN,
	PREENFM2_NRPN_ENV4_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV4_RELEASE,
	PREENFM2_NRPN_ENV4_RELEASE_LEVEL,

	PREENFM2_NRPN_ENV5_ATTK,
	PREENFM2_NRPN_ENV5_ATTK_LEVEL,
	PREENFM2_NRPN_ENV5_DECAY,
	PREENFM2_NRPN_ENV5_DECAY_LEVEL,
	PREENFM2_NRPN_ENV5_SUSTAIN,
	PREENFM2_NRPN_ENV5_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV5_RELEASE,
	PREENFM2_NRPN_ENV5_RELEASE_LEVEL,

	PREENFM2_NRPN_ENV6_ATTK,
	PREENFM2_NRPN_ENV6_ATTK_LEVEL,
	PREENFM2_NRPN_ENV6_DECAY,
	PREENFM2_NRPN_ENV6_DECAY_LEVEL,
	PREENFM2_NRPN_ENV6_SUSTAIN,
	PREENFM2_NRPN_ENV6_SUSTAIN_LEVEL,
	PREENFM2_NRPN_ENV6_RELEASE,
	PREENFM2_NRPN_ENV6_RELEASE_LEVEL,

	PREENFM2_NRPN_MTX1_SOURCE = 116,
	PREENFM2_NRPN_MTX1_MULTIPLIER,
	PREENFM2_NRPN_MTX1_DESTINATION,
	PREENFM2_NRPN_MTX1_EMPTY,

	PREENFM2_NRPN_MTX2_SOURCE,
	PREENFM2_NRPN_MTX2_MULTIPLIER,
	PREENFM2_NRPN_MTX2_DESTINATION,
	PREENFM2_NRPN_MTX2_EMPTY,

	PREENFM2_NRPN_MTX3_SOURCE,
	PREENFM2_NRPN_MTX3_MULTIPLIER,
	PREENFM2_NRPN_MTX3_DESTINATION,
	PREENFM2_NRPN_MTX3_EMPTY,

	PREENFM2_NRPN_MTX4_SOURCE,
	PREENFM2_NRPN_MTX4_MULTIPLIER,
	PREENFM2_NRPN_MTX4_DESTINATION,
	PREENFM2_NRPN_MTX4_EMPTY,

	PREENFM2_NRPN_MTX5_SOURCE,
	PREENFM2_NRPN_MTX5_MULTIPLIER,
	PREENFM2_NRPN_MTX5_DESTINATION,
	PREENFM2_NRPN_MTX5_EMPTY,

	PREENFM2_NRPN_MTX6_SOURCE,
	PREENFM2_NRPN_MTX6_MULTIPLIER,
	PREENFM2_NRPN_MTX6_DESTINATION,
	PREENFM2_NRPN_MTX6_EMPTY,

	PREENFM2_NRPN_MTX7_SOURCE,
	PREENFM2_NRPN_MTX7_MULTIPLIER,
	PREENFM2_NRPN_MTX7_DESTINATION,
	PREENFM2_NRPN_MTX7_EMPTY,

	PREENFM2_NRPN_MTX8_SOURCE,
	PREENFM2_NRPN_MTX8_MULTIPLIER,
	PREENFM2_NRPN_MTX8_DESTINATION,
	PREENFM2_NRPN_MTX8_EMPTY,

	PREENFM2_NRPN_MTX9_SOURCE,
	PREENFM2_NRPN_MTX9_MULTIPLIER,
	PREENFM2_NRPN_MTX9_DESTINATION,
	PREENFM2_NRPN_MTX9_EMPTY,

	PREENFM2_NRPN_MTX10_SOURCE,
	PREENFM2_NRPN_MTX10_MULTIPLIER,
	PREENFM2_NRPN_MTX10_DESTINATION,
	PREENFM2_NRPN_MTX10_EMPTY,

	PREENFM2_NRPN_MTX11_SOURCE,
	PREENFM2_NRPN_MTX11_MULTIPLIER,
	PREENFM2_NRPN_MTX11_DESTINATION,
	PREENFM2_NRPN_MTX11_EMPTY,

	PREENFM2_NRPN_MTX12_SOURCE,
	PREENFM2_NRPN_MTX12_MULTIPLIER,
	PREENFM2_NRPN_MTX12_DESTINATION,
	PREENFM2_NRPN_MTX12_EMPTY


};

#endif  // PREENNRPN_H_INCLUDED
